#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Aug 07 21:05:46 BST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=COBBLEVERSE - Shaders (High Quality)
